default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: InstaApp_development
test:
  <<: *default
  database: InstaApp_test
production:
  <<: *default
  database: InstaApp_production
  username: InstaApp
  password: <%= ENV['INSTAAPP_DATABASE_PASSWORD'] %>
